LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := RemovePackages
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_OVERRIDES_PACKAGES := Aperture AmbientSensePrebuilt
LOCAL_OVERRIDES_PACKAGES += AppDirectedSMSService
LOCAL_OVERRIDES_PACKAGES += CalculatorGooglePrebuilt
LOCAL_OVERRIDES_PACKAGES += CalendarGooglePrebuilt Drive
LOCAL_OVERRIDES_PACKAGES += FilesPrebuilt GoogleTTS
LOCAL_OVERRIDES_PACKAGES += Maps Photos
LOCAL_OVERRIDES_PACKAGES += SafetyHubPrebuilt
LOCAL_OVERRIDES_PACKAGES += talkback
LOCAL_UNINSTALLABLE_MODULE := true
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_SRC_FILES := /dev/null
include $(BUILD_PREBUILT)
